# Generated by Django 6.0.6 on 2026-06-20 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_gift_giftassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('destination_wilaya', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Dispatch', 'Pending Dispatch'), ('In Transit', 'In Transit'), ('Arrived', 'Arrived'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending Dispatch', max_length=30)),
                ('route', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_dispatches', to='apis.warehouse')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_dispatches', to='apis.warehouse')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='apis.employee')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='apis.gift')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_dispatches', to='apis.warehouse')),
            ],
        ),
    ]
