# Generated by Django 6.0.3 on 2026-06-21 11:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_dispatchorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gift',
            name='points_cost',
            field=models.IntegerField(default=0, help_text='Loyalty points needed to redeem this gift'),
        ),
        migrations.AddField(
            model_name='gift',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price in Algerian Dinar (DZD)', max_digits=12),
        ),
    ]
