# Generated by Django 6.0.6 on 2026-07-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_employee_loyalty_points_gift_points_cost_gift_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchorder',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
