# Generated by Django 6.0.6 on 2026-07-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_dispatchorder_current_lat_dispatchorder_current_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
