# Generated by Django 6.0.6 on 2026-07-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_employee_home_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='zones',
            field=models.IntegerField(default=1),
        ),
    ]
